wrtnlabs/connectors

src/api/functional/connector/sweet_tacker/tracking_info/index.ts
src/controllers/connector/arxiv_search/ArxivSearchController.ts
src/controllers/connector/csv/CsvController.ts
src/controllers/connector/daum/DaumController.ts
src/controllers/connector/gmail/GmailController.ts
src/controllers/connector/google-docs/GoogleDocsController.ts
src/controllers/connector/google-sheet/GoogleSheetController.ts
src/controllers/connector/google_calendar/GoogleCalendarController.ts
src/controllers/connector/google_drive/GoogleDriveController.ts
src/controllers/connector/google_scholar/GoogleScholarController.ts
src/controllers/connector/imweb/ImwebController.ts
src/controllers/connector/kakao_talk/KakaoTalkController.ts
src/controllers/connector/naver/NaverController.ts
src/controllers/connector/sweet_tracker/SweetTrackerController.ts
src/controllers/connector/youtube_search/YoutubeSearchController.ts
src/controllers/connector/zoom/ZoomController.ts

- 단독 사용가능한 커넥터들에 `standalone` 데코레이터 추가

feat: add `Standalone` decorator

---

src/api/functional/connector/notion/database_item/index.ts
src/api/functional/connector/notion/find_item/index.ts
src/api/functional/connector/notion/find_item_list/index.ts
src/api/functional/connector/notion/get/database_info/index.ts
src/api/functional/connector/notion/get/page/index.ts
src/api/functional/connector/notion/get/users/index.ts
src/api/functional/connector/notion/get_page_by_title/index.ts
src/api/functional/connector/notion/page/content/index.ts
src/api/functional/connector/notion/page/index.ts
src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts

secret key naming 대문자에서 소문자로 변경

refactor: secret key naming

---

src/api/structures/connector/kakao_talk/IKakaoTalk.ts
src/providers/connector/kakao_talk/KakaoTalkProvider.ts
test/features/api/connector/kakao_talk/test_api_kakao_talk.ts

카카오 타입에 title, description을 추가하였습니다.
주석에 따라 UI가 달리 보여질 거라는 걸 몰랐습니다. :(

feat: Modify the type to a clearer meaning

---

nestia.config.ts

No beautify `swagger.json` file

---

src/controllers/connector/open_data/OpenDataController.ts
src/controllers/connector/sweet_tracker/SweetTrackerController.ts

fix: 누락된 `Standalone` 추가 & comment 일부 수정

---

nestia.config.ts
src/executable/openai.ts

Add server urls

---

src/services/openai/IOpenAiDocument.ts
src/services/openai/OpenAiConverter.ts

Make `IOpenAiDocument.IOperation.parameters` to be compatible.

---

src/services/openai/OpenAiFetcher.ts

Exact OpenAiFetcher

---

packages/api/.gitignore
src/executable/openai.ts

Add version.json

---

src/api/functional/connector/sweet_tacker/get_companies/index.ts
src/api/functional/connector/sweet_tacker/get_companies/recommended/index.ts
src/api/functional/connector/sweet_tacker/tracking_info/index.ts
src/controllers/connector/notion/NotionController.ts
src/utils/retry.ts

함수를 받아 N번까지 재실행되도록 함수를 수정하는 로직을 만들었습니다.
멱등한 함수에만 사용해야 하기 때문에 데이터를 수정하거나 추가할 때에는 사용하지 말거나 멱등한지 주의깊게 봐야 합니다.
수정 때문에라도 PUT PATCH를 앞으로 잘 구분해야 할 거 같습니다. ( PUT은 안심하고 retry할 수 있도록 )

retry 함수 추가

---

src/api/structures/connector/story_generator/IStoryGenerator.ts
src/providers/connector/story_generator/StoryGeneratorProvider.ts

Update story generator prompt

---

src/controllers/connector/google_slides/GoogleSlidesModule.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
test/features/api/connector/google_slides/test_api_connector_google_slides.ts

quick fix - update google slides connector to accept s3 urls and use presigned url (need a more centralized version later)

---

.github/workflows/version-bump.yml

버전 관리에 크게 의미를 둘 필요 없고 그냥 이전과 다르기만 하면 된다고 하셔서 Main 기준으로 그냥 `npm version patch` 돌리게 했습니다.
맨 끝 패치 버전만 그냥 이전보다 1 높여주는 명령어입니다.

feat: add `version-bump.yml`

---

src/services/openai/OpenAiConverter.ts

Fix openai.json

---

src/controllers/connector/story_image_generator/StoryImageGeneratorModule.ts
src/providers/connector/story_image_generator/StoryImageGeneratorProvider.ts

- [V] passed test code
- [V] api tags
- [V] RouteIcon
- [V] docs (summary, input, returns )

feat: change dall-e-3 to sdxl-beta story-image-generator

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts

- [V] passed test code
- [V] api tags
- [V] RouteIcon
- [V] docs (summary, input, returns )

feat: notion prerequsite

---

src/providers/connector/stable_diffusion_beta/StableDiffusionBetaProvider.ts
src/providers/connector/story_image_generator/StoryImageGeneratorProvider.ts

- [V] passed test code
- [V] api tags
- [V] RouteIcon
- [V] docs (summary, input, returns )

fix: story image gen not use presigned url

---

package-lock.json
package.json

Bump `@wrtnio/openai-function-schema` up

---

src/api/structures/connector/common/ISecretValue.ts
src/api/structures/connector/gmail/IGmail.ts
src/api/structures/connector/google_calendar/IGoogleCalendar.ts
src/api/structures/connector/google_docs/IGoogleDocs.ts
src/api/structures/connector/google_drive/IGoogleDrive.ts
src/api/structures/connector/notion/INotion.ts
src/controllers/connector/gmail/GmailController.ts
src/controllers/connector/google-docs/GoogleDocsController.ts
src/controllers/connector/google_calendar/GoogleCalendarController.ts
src/controllers/connector/google_drive/GoogleDriveController.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/gmail/GmailProvider.ts
src/providers/connector/google_calendar/GoogleCalendarProvider.ts
src/providers/connector/google_docs/GoogleDocsProvider.ts
src/providers/connector/google_drive/GoogleDriveProvider.ts
src/providers/connector/notion/NotionProvider.ts

fix: secret type and naming

---

src/api/functional/connector/kakao_navi/get_future_directions/index.ts
src/api/structures/connector/kakao_navi/IKakaoNavi.ts
src/controllers/connector/kakao_navi/KakaoNaviController.ts
src/providers/connector/kakao_navi/KakaoNaviProvider.ts
test/features/api/connector/kakao_navi/test_api_connector_kakao_navi.ts

fix: kakao_navi response type

---

src/providers/connector/notion/NotionProvider.ts

fix: test code failed

---

src/api/structures/connector/open_data/IMOLIT.ts
src/controllers/connector/open_data/OpenDataController.ts
src/providers/connector/open_data/OpenDataProvider.ts
src/utils/retry.ts

- [v] passed test code
- 아까 그 Prerequsite 유니온 타입을 해결합니다.

fix: fix union type of prerequisite

---

src/controllers/connector/gmail/GmailController.ts
src/controllers/connector/google-docs/GoogleDocsController.ts
src/controllers/connector/google_calendar/GoogleCalendarController.ts
src/controllers/connector/google_drive/GoogleDriveController.ts
src/controllers/connector/notion/NotionController.ts

refactor: change title to summary tag

---

src/api/structures/connector/google_calendar/IGoogleCalendar.ts

refactor: google calendar read event interface

---

nestia-configs/tags/arxiv-search.nestia.config.ts
nestia-configs/tags/aws.nestia.config.ts
nestia-configs/tags/chatbot.nestia.config.ts
nestia-configs/tags/csv.nestia.config.ts
nestia-configs/tags/daum.nestia.config.ts
nestia-configs/tags/figma.nestia.config.ts
nestia-configs/tags/google-calendar.nestia.config.ts
nestia-configs/tags/google-gmail.nestia.config.ts
nestia-configs/tags/google-scholar.nestia.config.ts
nestia-configs/tags/google-search.nestia.config.ts
nestia-configs/tags/google-shopping.nestia.config.ts
nestia-configs/tags/google.nestia.config.ts
nestia-configs/tags/hancell.nestia.config.ts
nestia-configs/tags/imweb.nestia.config.ts
nestia-configs/tags/kakao-map.nestia.config.ts
nestia-configs/tags/kakao-navi.nestia.config.ts
nestia-configs/tags/kakao-talk.nestia.config.ts
nestia-configs/tags/marketing-copy.nestia.config.ts
nestia-configs/tags/naver.nestia.config.ts
nestia-configs/tags/notion.nestia.config.ts
nestia-configs/tags/story-generator.nestai.config.ts
nestia-configs/tags/tool.nestia.config.ts
nestia-configs/tags/youtube-search.nestia.config.ts
src/executable/categorize.ts
src/providers/open_ai/OpenAIModule.ts
src/swaggers/tags/GoogleTagModule.ts
src/swaggers/tags/StoryGeneratorTagModule.ts

각 Tag 별 커넥터 스웨거 분리

---

.gitignore
src/providers/open_ai/OpenAIModule.ts

OpenAIModule 에 pinoLoggerParams 추가

---

src/providers/connector/aws/AwsProvider.ts
src/providers/connector/dall_e_3/DallE3Provider.ts
src/providers/connector/stable_diffusion_beta/StableDiffusionBetaProvider.ts

feat: s3 url content type for image

---

src/api/structures/connector/marketing/IMarketingCopyGenerator.ts
src/providers/connector/aws/AwsProvider.ts
src/providers/connector/dall_e_3/DallE3Provider.ts
src/providers/connector/stable_diffusion_beta/StableDiffusionBetaProvider.ts
src/providers/connector/story_image_generator/StoryImageGeneratorProvider.ts

refactor: generate image not use presigned url

---

src/utils/retry.ts
test/inhouse/api/connector/rag/test_api_connector_rag.ts

제가 코드를 바보 같이 짰었네요.
retry하는 구글 코드가 find 안에 async를 넣은 상태였더라구요. 당연히 안되는 건데 바보 같은 짓을...

test: test google ads only in CI/CD

---

src/controllers/connector/rag/RagController.ts
src/providers/connector/rag/RagProvider.ts

refactor: rag generate logic

---

src/controllers/connector/rag/RagController.ts

Change type of `RagController.generate()`

---

package-lock.json
package.json

fix: version of openai-function-schema

---

website/.gitignore
website/build/swagger.js

Website source dir refector

---

nestia-configs/google.nestia.config.ts

Rename google storage swagger file

---

src/api/structures/connector/imweb/IImweb.ts
src/controllers/connector/imweb/ImwebController.ts
src/providers/connector/imweb/ImwebProvider.ts
test/features/api/connector/imweb/test_api_connector_imweb.ts

- 번역 및 스코프 수정
- 아임웹은 OAuth 연동이 아니라 API Key를 입력 받아야 하기 때문에 Secret 타입으로 대응이 안됩니다.

translate imweb connector and remove secret keys

---

src/api/structures/connector/google_flight/IGoogleFlight.ts
src/controllers/connector/google_flight/GoogleFlightController.ts
src/providers/connector/google_flight/GoogleFlightProvider.ts
test/features/api/connector/google_flight/test_api_connector_google_flight.ts

refactor: request interface

---

src/api/structures/connector/open_data/IOpenData.ts
src/controllers/connector/open_data/OpenDataController.ts
src/providers/connector/open_data/OpenDataProvider.ts
test/features/api/connector/open_data/test_api_connector_open_data_short_term_forecast.ts

- translate open data connectors from Korean to English
- add new type of get short-term forecast connector

translate opendata & fix short-term forecast connector

---

src/api/structures/connector/rag/IRag.ts
src/controllers/connector/rag/RagController.ts
src/providers/connector/rag/RagProvider.ts
test/inhouse/api/connector/rag/test_api_connector_rag.ts

refactor: rag request interface

---

src/api/structures/connector/google_slides/IGoogleSlides.ts
src/api/structures/connector/imweb/IImweb.ts
src/controllers/connector/google_slides/GoogleSlidesController.ts
src/executable/connector-separation.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
src/providers/connector/open_data/OpenDataProvider.ts
test/features/api/connector/google_slides/test_api_connector_google_slides.ts

- `Presentation` 타입을 리턴하지 않고 void 리턴으로 변경.
- 1140K token to 8.5k token...

reduce google slides

---

package-lock.json
package.json

Bump up dependencies

---

packages/api/swagger.korean.json
src/executable/translate.ts

Complete translator

---

src/ConnectorGlobal.ts
src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/ConnectorModule.ts
src/controllers/connector/slack/SlackController.ts
src/controllers/connector/slack/SlackModule.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

- private 채널 조회
- public 채널 조회
- im 채널 ( 자기 자신에게 DM 보내는 채널 ) 조회
- channel histories 조회 ( = 채팅 내역 )

slack connectors

---

src/controllers/connector/google_slides/GoogleSlidesController.ts
src/controllers/connector/story_generator/StoryGeneratorController.ts

refactor: enhance description

---

src/api/structures/common/IConnector.ts
src/api/structures/connector/google_ads/IGoogleAds.ts
src/api/structures/connector/google_slides/IGoogleSlides.ts
src/api/structures/connector/marketing/IMarketingCopyGenerator.ts
src/api/structures/zoom/IZoom.ts
src/controllers/connector/google_ads/GoogleAdsController.ts
src/utils/types/MyPartial.ts

- 주석에 타입스크립트 기본 타입인 `Partial` 타입의 주석이 달리는 것을 막기 위해 주석이 없는 `MyPartial` 타입을 정의합니다.

feat: add custom partial type

---

src/controllers/connector/airport_information/AirportInformationController.ts
src/controllers/connector/dall_e_3/DallE3Controller.ts
src/controllers/connector/google_flight/GoogleFlightController.ts
src/controllers/connector/google_hotel/GoolgeHotelController.ts
src/controllers/connector/google_slides/GoogleSlidesController.ts
src/controllers/connector/rag/RagController.ts

feat: add icon

---

src/api/structures/connector/gmail/IGmail.ts
src/api/structures/connector/google_hotel/IGoogleHotel.ts
src/providers/connector/google_hotel/GoogleHotelProvider.ts

chore: enhance description

---

src/providers/connector/slack/SlackProvider.ts

fix: fix slack message

---

src/api/structures/connector/google_slides/IGoogleSlides.ts
src/controllers/connector/google_slides/GoogleSlidesController.ts

chore: enhance description google slide

---

src/api/structures/connector/google_flight/IGoogleFlight.ts

chore: enhance description google flight

---

src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts

fix: make user id optional

---

src/controllers/connector/google_flight/GoogleFlightController.ts
src/providers/connector/google_flight/GoogleFlightProvider.ts
test/features/api/connector/google_flight/test_api_connector_google_flight.ts

feat: refactor google flight

---

src/providers/connector/google_hotel/GoogleHotelProvider.ts

feat: google hotel refactor

---

src/providers/connector/google_flight/GoogleFlightProvider.ts

fix: google flight bug

---

src/providers/connector/google_hotel/GoogleHotelProvider.ts

fix: google hotel

---

src/api/structures/connector/google_flight/IGoogleFlight.ts
src/providers/connector/google_flight/GoogleFlightProvider.ts
test/features/api/connector/google_flight/test_api_connector_google_flight.ts

fix: google flight

---

src/providers/connector/google_hotel/GoogleHotelProvider.ts

fix: google hotel amenities undefined

---

src/providers/connector/rag/RagProvider.ts

chore: rag x-service-id change

---

src/api/structures/connector/google_hotel/IGoogleHotel.ts
src/providers/connector/google_hotel/GoogleHotelProvider.ts
test/features/api/connector/google_hotel/test_api_connector_google_hotel.ts

fix: undefined field

---

nestia-configs/google-flight.nestia.config.ts
nestia-configs/google-trend.nestia.config.ts
src/api/structures/connector/google_trend/IGoogleTrend.ts
src/controllers/connector/ConnectorModule.ts
src/controllers/connector/google_trend/GoogleTrendController.ts
src/controllers/connector/google_trend/GoogleTrendModule.ts
src/providers/connector/google_trend/GoogleTrendProvider.ts
src/swaggers/MarketingModule.ts
test/features/api/connector/google_trend/test_api_connector_google_trend.ts

feat: add google trend

---

nestia-configs/google-docs.nestia.config.ts
nestia-configs/google-drive.nestia.config.ts
nestia-configs/google-sheet.nestia.config.ts
nestia-configs/google-slide.nestia.config.ts
nestia-configs/open-data.nestia.config.ts

구글 커넥터 Swagger 분리

---

src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

4가지 커넥터를 추가합니다.
- 읽음 처리 기능
- 예약 메시지 기능
- 예약 메시지 조회 기능
- 예약 메세지 삭제 기능

new slack connectors for schedule messages

---

src/api/structures/connector/slack/ISlack.ts

fix: found new pattern of channel id in slack

---

package-lock.json
package.json

New property `strict` has been newly added to OpenAI function calling schema.
Here is the related article.
https://openai.com/index/introducing-structured-outputs-in-the-api/

Adapt wrtnio/openai-function-schema#20.

---

src/providers/connector/google_flight/GoogleFlightProvider.ts

feat: add shortlink for google flight book link

---

src/api/structures/connector/jira/IJira.ts
src/controllers/connector/jira/JiraController.ts
src/providers/connector/jira/JiraProvider.ts
test/features/api/connector/jira/test_api_connector_get_issues.ts

[DRAFT] jira connectors

---

src/api/structures/connector/google_shopping/IGoogleShopping.ts
src/providers/connector/google_shopping/GoogleShoppingProvider.ts

fix: source undefiend

---

src/api/structures/connector/google_shopping/IGoogleShopping.ts
src/providers/connector/google_shopping/GoogleShoppingProvider.ts

fix: delivery cost undefiend

---

src/controllers/connector/jira/JiraController.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts

- 간헐적으로 슬랙이 깨지는 문제가 charset 문제일 수 있겠단 생각이 들어 수정해봅니다.

add chaset to slack apis and add comments

---

test/features/api/connector/google_flight/test_api_connector_google_flight.ts
test/features/api/connector/google_hotel/test_api_connector_google_hotel.ts

fix: date bug

---

src/api/structures/connector/google_search/IGoogleSearch.ts

fix: google search snippet allow undefined

---

src/providers/connector/aws/AwsProvider.ts

fix: s3 key decodeuricomponent

---

src/api/structures/connector/github/IGithub.ts
src/api/structures/connector/jira/IJira.ts
src/controllers/connector/github/GithubController.ts

GitHub commit

---

src/api/structures/connector/rag/IRag.ts
src/controllers/connector/rag/RagController.ts
src/providers/connector/rag/RagProvider.ts
test/inhouse/api/connector/rag/test_api_connector_rag.ts

fix: fix rag histories type

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/controllers/connector/internal/google/GoogleController.ts
src/providers/connector/github/GithubProvider.ts
test/features/api/connector/github/test_api_connector_github_get_file_contents.ts

github file 조회 커넥터들

---

src/api/structures/connector/google_flight/IGoogleFlight.ts
src/api/structures/connector/google_hotel/IGoogleHotel.ts
src/api/structures/connector/short_link/IShortLink.ts
src/controllers/connector/ConnectorModule.ts
src/controllers/connector/google_flight/GoogleFlightModule.ts
src/controllers/connector/short_link/ShortLinkController.ts
src/controllers/connector/short_link/ShortLinkModule.ts
src/providers/connector/google_flight/GoogleFlightProvider.ts
src/providers/connector/google_hotel/GoogleHotelProvider.ts
src/providers/connector/short_link/ShortLinkProvider.ts
test/inhouse/api/connector/short_link/test_api_connector_short_link.ts

feat: short link provider create and bad request error when date is past

---

src/api/structures/connector/youtube_search/IYoutubeSearch.ts
src/controllers/connector/figma/FigmaController.ts
src/controllers/connector/figma/FigmaModule.ts
src/controllers/connector/zoom/ZoomController.ts
src/providers/connector/figma/FigmaProvider.ts
src/providers/connector/github/GithubProvider.ts
src/providers/connector/gmail/GmailProvider.ts
src/providers/connector/google_calendar/GoogleCalendarProvider.ts
src/providers/connector/google_docs/GoogleDocsProvider.ts
src/providers/connector/google_drive/GoogleDriveProvider.ts
src/providers/connector/google_sheet/GoogleSheetProvider.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
src/providers/connector/kakao_talk/KakaoTalkProvider.ts
src/providers/connector/notion/NotionProvider.ts
src/providers/connector/slack/SlackProvider.ts
src/providers/connector/zoom/ZoomProvider.ts
src/providers/internal/oauth_secret/OAuthSecretProvider.ts
src/providers/internal/oauth_secret/structures/IOAuthSecret.ts

feat: add get oauth secret

---

src/providers/connector/google_ads/GoogleAdsProvider.ts

feat: google ads refresh logic

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/aws/AwsProvider.ts
src/providers/connector/github/GithubProvider.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
src/providers/connector/rag/RagProvider.ts
test/features/api/connector/github/test_api_connector_github_analyze.ts
test/features/api/connector/github/test_api_connector_github_get_file_contents.ts
test/features/api/connector/github/test_api_connector_github_get_issues.ts
test/features/api/connector/github/test_api_connector_github_get_organization_repository.ts
test/features/api/connector/github/test_api_connector_github_get_organizations.ts
test/features/api/connector/github/test_api_connector_github_get_repositories.ts
test/features/api/connector/github/test_api_connector_github_organization_get_issues.ts
test/features/api/connector/github/test_api_connector_github_repository_get_issues.ts
test/features/api/connector/github/test_api_connector_github_users_get_received_events.ts

정규표현식 수정 및 깃허브 커넥터 다수 추가

---

src/api/structures/connector/github/IGithub.ts

fix: fix scope of getting issue connectors

---

src/providers/connector/notion/NotionProvider.ts

feat: add refresh logic create client

---

src/api/structures/connector/github/IGithub.ts

fix: getting issue require scopes, user and repo

---

src/api/structures/connector/google_calendar/IGoogleCalendar.ts

fix: add possible value for extract field

---

src/api/structures/connector/google_sheet/IGoogleSheet.ts
src/controllers/connector/google-sheet/GoogleSheetController.ts
src/providers/connector/google_calendar/GoogleCalendarProvider.ts
src/providers/connector/google_sheet/GoogleSheetProvider.ts
test/features/api/connector/google_sheet/test_api_connector_create_google_sheet.ts

feat: add google sheet

---

src/providers/connector/google_calendar/GoogleCalendarProvider.ts

refactor: parse event info logic

---

src/api/structures/connector/excel/IExcel.ts
src/controllers/connector/excel/ExcelController.ts
src/providers/connector/excel/ExcelProvider.ts
test/inhouse/api/connector/excel/test_api_connector_excel.ts

테스트 코드 통과하였고 리뷰 요청은 하되 선 Merge 하도록 하겠습니다. ( 개발 환경에서 실제로 돌려볼 예정 )

add comments to excel connector and create sheet connector

---

src/api/structures/connector/sweet_tracker/ISweetTacker.ts
src/controllers/connector/sweet_tracker/SweetTrackerController.ts
test/features/api/connector/sweet_tracker/test_api_connector_sweet_tracker.ts

수취인의 address의 타입이 null일 수도 있습니다. ( 받는 사람의 주소가 null 이라고? )

fix: fix receiver address type in sweet-tracker

---

src/api/structures/connector/excel/IExcel.ts
src/controllers/connector/excel/ExcelController.ts

chore: Add docs for generating excel file and data

---

src/api/structures/connector/google_calendar/IGoogleCalendar.ts
src/providers/connector/google_calendar/GoogleCalendarProvider.ts
test/features/api/connector/google_calendar/test_api_connector_google_calendar.ts

fix: google calendar bug

---

src/api/structures/connector/github/IGithub.ts
src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/github/GithubController.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/github/GithubProvider.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/github/test_api_connector_github_get_commit.ts
test/features/api/connector/slack/test_api_connector_slack.ts

fix: add datetime format option in salck getting channel histories connector

---

src/api/structures/connector/google_sheet/IGoogleSheet.ts
src/controllers/connector/google-sheet/GoogleSheetController.ts
src/providers/connector/google_sheet/GoogleSheetProvider.ts
test/features/api/connector/google_sheet/test_api_connector_append_google_sheet.ts

feat: add append value google sheet

---

src/controllers/connector/notion/NotionController.ts

fix: remove deprecated connector

---

src/api/structures/connector/open_data/IOpenData.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/notion/NotionProvider.ts

슬랙 및 시가총액 공공 데이터에 대한 커넥터 프롬프트 수정

---

src/api/structures/connector/open_data/MSIT.ts
src/controllers/connector/open_data/OpenDataController.ts
src/providers/connector/open_data/OpenDataProvider.ts
test/features/api/connector/open_data/test_api_connector_open_data.ts

우편주소, 동체계, 도로명주소를 대응하기 위한 공공데이터 추가

---

src/api/structures/connector/open_data/ILH.ts
src/controllers/connector/open_data/OpenDataController.ts
src/providers/connector/open_data/OpenDataProvider.ts

LH 공공데이터 프롬프트 개선

---

src/api/structures/connector/open_data/IMOLIT.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/open_data/OpenDataProvider.ts
test/features/api/connector/open_data/test_api_connector_open_data.ts

저작권자 이름을 기준으로 검색 가능하게 기능 수정

---

src/api/structures/connector/open_data/IOpenData.ts
src/providers/connector/open_data/OpenDataProvider.ts

fix: 공공데이터 형식에 맞게 데이터 포맷팅하는 기능 추가 및 형식에 대한 주석 추가

---

src/api/structures/connector/rag/IRag.ts

fix: rag analyze input naming

---

src/api/structures/connector/open_data/MSIT.ts
src/controllers/connector/open_data/OpenDataController.ts
src/providers/connector/open_data/OpenDataProvider.ts
test/features/api/connector/open_data/test_api_connector_open_data_get_address.ts

우편주소를 지번 주소, 도로명 주소로 변환하는 기능

---

src/api/structures/connector/excel/IExcel.ts
src/api/structures/connector/open_data/IMOLIT.ts
src/api/structures/connector/open_data/KoreaCopyrightCommission.ts
src/api/structures/connector/open_data/MSIT.ts
src/controllers/connector/excel/ExcelController.ts
src/controllers/connector/open_data/OpenDataController.ts
test/features/api/connector/open_data/test_api_connector_open_data_get_address.ts

엑셀 파일에 로우를 추가하는 기능을 업로드가 필요한 경우와 필요하지 않은 경우로 분리

---

src/api/structures/connector/rag/IRag.ts
src/controllers/connector/rag/RagController.ts
src/providers/connector/github/GithubProvider.ts
src/providers/connector/rag/RagProvider.ts
test/inhouse/api/connector/rag/test_api_connector_rag.ts

fix: rag analyze input type

---

src/api/structures/connector/open_data/INIA.ts
src/controllers/connector/kakao_map/KakaoMapController.ts
src/controllers/connector/open_data/OpenDataController.ts

공공데이터 중 주차장 정보 조회 시 필요한 도로명 주소를 카카오맵에서 획득하도록 Prerequisite 추가

---

.github/workflows/build.yml
src/api/structures/connector/github/IGithub.ts
src/api/structures/connector/google_ads/IGoogleAds.ts
src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/github/GithubController.ts
src/controllers/connector/google_ads/GoogleAdsController.ts
src/controllers/connector/open_data/OpenDataController.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/github/GithubProvider.ts
src/providers/connector/google_map/GoogleMapProvider.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/github/test_api_connector_github_get_users_pinned_repositories.ts
test/features/api/connector/open_data/test_api_connector_open_data.ts
test/features/api/connector/slack/test_api_connector_slack.ts

240908 fix

---

src/api/structures/connector/github/IGithub.ts
src/api/structures/connector/open_data/IOpenData.ts
src/providers/connector/github/GithubProvider.ts
test/features/api/connector/open_data/test_api_connector_open_data.ts
test/features/api/connector/open_data/test_api_connector_open_data_get_standard_region_code_list.ts

feat: 행정동 코드 조회 시 지역 이름을 정확히 입력하도록 타입과 프롬프트를 추가

---

src/api/structures/connector/gmail/IGmail.ts
src/controllers/connector/gmail/GmailController.ts
src/providers/connector/gmail/GmailProvider.ts
test/features/api/connector/gmail/test_api_connector_gmail.ts
test/features/api/connector/gmail/test_api_connector_gmail_create_draft.ts
test/features/api/connector/gmail/test_api_connector_gmail_send_email_with_file.ts
test/features/api/connector/open_data/test_api_connector_open_data.ts

gmail에 파일 첨부 가능하도록 프로퍼티 추가

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/excel/ExcelProvider.ts

시트 이름이 주어지지 않은 경우는 시트를 자동 추가하지 않게 기능 수정 & github 타입 수정

---

package-lock.json
package.json

Revert "chore(deps): bump @samchon/openapi from 0.4.9 to 1.0.0 in the samchon group"

---

src/api/structures/connector/gmail/IGmail.ts
src/providers/connector/google_flight/GoogleFlightProvider.ts

fix: delete short url and add description gmail send for link or url

---

src/api/structures/connector/naver/INaver.ts
src/controllers/connector/naver/NaverController.ts
src/providers/connector/naver/NaverProvider.ts
test/features/api/connector/naver/test_api_connector_read_news_naver.ts

feat: naver news connector

---

src/api/structures/connector/naver/INaver.ts
src/controllers/connector/naver/NaverController.ts

fix: naver lastBuildDate is not date-format

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/github/GithubProvider.ts
src/utils/types/PickPartial.ts
test/features/api/connector/github/test_api_connector_github_create_branch.ts
test/features/api/connector/github/test_api_connector_github_create_file_content.ts
test/features/api/connector/github/test_api_connector_github_create_issue.ts
test/features/api/connector/github/test_api_connector_github_repository_get_issues.ts
test/features/api/connector/github/test_api_connector_github_update_issue.ts

github create branch, commit, PR

---

package-lock.json
package.json
src/api/structures/connector/jira/IJira.ts
src/controllers/connector/jira/JiraController.ts
src/providers/connector/jira/JiraProvider.ts
src/utils/markdownToJiraBlock.ts
test/features/api/connector/jira/test_api_connector_jira_assign_and_unassign.ts
test/features/api/connector/jira/test_api_connector_jira_comments.ts
test/features/api/connector/jira/test_api_connector_jira_create_issue.ts
test/features/api/connector/jira/test_api_connector_jira_create_issue_by_markdown.ts
test/features/api/connector/jira/test_api_connector_jira_update_issue.ts

마크다운을 Jira block으로 변환하는 기능

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/github/GithubProvider.ts
test/features/api/connector/github/test_api_connector_github_read_pull_request_diff.ts
test/features/api/connector/github/test_api_connector_github_read_pull_request_files.ts
test/features/api/connector/github/test_api_connector_github_read_pull_reuqest_commits.ts
test/features/api/connector/github/test_api_connector_github_read_pull_reuqest_detail.ts

PR 상세 조회 및 PR의 파일, diff, 커밋 내역을 조회하는 기능

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/github/GithubProvider.ts
test/features/api/connector/github/test_api_connector_github_repository_get_pull_requests.ts

PR 조회 시 per_page을 전달하지 않은 경우에 대한 기본 값 추가 및 프롬프트 수정

---

src/controllers/connector/github/GithubController.ts

feat: 이번에 추가된 기능들을 더 잘 선택하도록 하기 위한 주석 추가

---

src/api/structures/connector/google_map/IGoogleMap.ts
src/controllers/connector/github/GithubController.ts

더 이상 사용되지 않는 커넥터 2건 hidden 처리 및 구글 맵의 타입 수정

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/github/GithubProvider.ts
test/features/api/connector/github/test_api_connector_github_create_file_content.ts
test/features/api/connector/github/test_api_connector_github_repos_get_collaborators.ts
test/features/api/connector/github/test_api_connector_github_update_file_content.ts

to delete file content and to get collaborator connector in github

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/github/GithubProvider.ts
test/features/api/connector/github/test_api_connector_github_issues_get_comments.ts
test/features/api/connector/github/test_api_connector_github_read_pull_request_requested_reviewers.ts
test/features/api/connector/github/test_api_connector_github_read_pull_request_reviews.ts
test/inhouse/api/connector/excel/test_api_connector_excel.ts

리뷰 요청 및 리뷰 조회, PR과 이슈에 대한 댓글을 조회하는 커넥터 추가

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/github/GithubProvider.ts
test/features/api/connector/github/test_api_connector_github_request_review.ts

리뷰 요청 및 리뷰 요청 취소 커넥터 추가

---

src/providers/connector/calendly/CalendlyProvider.ts

fix: fix calendly refresh token type

---

src/providers/connector/typeform/TypeformProvider.ts

fix: typeform refresh token update logic

---

package-lock.json
package.json
src/api/structures/connector/google_slides/IGoogleSlides.ts
src/controllers/connector/google_slides/GoogleSlidesController.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
test/features/api/connector/calendly/test_api_connector_calendly_create_one_off_event_types.ts
test/features/api/connector/calendly/test_api_connector_calendly_create_scheduling_links.ts
test/features/api/connector/calendly/test_api_connector_calendly_events_get_invitees.ts
test/features/api/connector/calendly/test_api_connector_calendly_events_invitees_get_cancel_link.ts
test/features/api/connector/calendly/test_api_connector_calendly_events_invites_get_one_invite.ts
test/features/api/connector/calendly/test_api_connector_calendly_get_event_types.ts
test/features/api/connector/calendly/test_api_connector_calendly_get_one_scheduled_event.ts
test/features/api/connector/calendly/test_api_connector_calendly_get_scheduled_events.ts
test/features/api/connector/calendly/test_api_connector_calendly_users_get_me.ts
test/features/api/connector/google_slides/test_api_connector_google_slides_by_types.ts

refactor google slide

---

src/providers/connector/google_slides/GoogleSlidesProvider.ts

fix: 이미지의 index에 따라 다르게 들어가게 수정

---

src/api/structures/connector/google_slides/IGoogleSlides.ts
src/controllers/connector/google_slides/GoogleSlidesController.ts

google slide texts

---

src/controllers/connector/ai_search/AISearchController.ts

chore: make ai-search hidden

---

package.json

deploy again

---

package.json

chore: update package's description

---

src/providers/connector/airport_information/AirportInformationProvider.ts
src/providers/connector/aws/AwsProvider.ts
src/providers/connector/csv/CsvProvider.ts
src/providers/connector/google_sheet/GoogleSheetProvider.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
src/providers/connector/kakao_navi/KakaoNaviProvider.ts
src/providers/connector/rag/RagProvider.ts
src/providers/connector/youtube_search/YoutubeSearchProvider.ts
src/providers/swagger/SwaggerProvider.ts
test/features/api/connector/google_slides/test_api_connector_google_slides_by_types.ts

fix regexp for google slides and all of connectors are using awsProvider

---

src/providers/connector/marp/MarpProvider.ts

fix: use npx instread of local cli

---

src/controllers/connector/csv/CsvController.ts
src/controllers/connector/csv/CsvModule.ts
src/controllers/connector/excel/ExcelController.ts
src/controllers/connector/excel/ExcelModule.ts
src/providers/connector/aws/AwsProvider.ts
src/providers/connector/csv/CsvProvider.ts
src/providers/connector/excel/ExcelProvider.ts
src/providers/connector/google_scholar/GoogleScholarProvider.ts

fix: connector bugs

---

src/providers/connector/google_hotel/GoogleHotelProvider.ts

fix: get env key

---

src/api/structures/common/IConnector.ts
src/api/structures/connector/google_map/IGoogleMap.ts
src/api/structures/connector/youtube_search/IYoutubeSearch.ts
src/providers/connector/google_map/GoogleMapProvider.ts

fix: keyword add tags minlength 1 and google map result not interable

---

src/api/structures/connector/github/IGithub.ts
src/api/structures/connector/sweet_tracker/ISweetTacker.ts
src/providers/connector/github/GithubProvider.ts
test/features/api/connector/github/test_api_connector_github_get_file_contents.ts

택배 배송 타입 수정 및 github 파일 검색 시 없을 경우 에러 대신 null 타입을 가지는 객체 리턴

---

src/api/structures/connector/sweet_tracker/ISweetTacker.ts

fix: 남은 프로퍼티도 옵셔널로 변경

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/notion/test_api_connector_notion_get_page_contents.ts

노션 페이지 상세 내역을 조회하는 기능을 추가

---

src/api/structures/connector/google_slides/IGoogleSlides.ts

구글 슬라이드 이미지가 형식에 안맞거나 존재하지 않는 경우는 안된다는 주석 추가

---

src/ConnectorGlobal.ts
src/api/structures/connector/open_data/IOpenData.ts
src/api/structures/connector/open_weather/IOpenWeather.ts
src/controllers/connector/open_data/OpenDataController.ts
src/providers/connector/open_data/OpenDataProvider.ts
test/features/api/connector/open_data/test_api_connector_open_data_short_term_forecast.ts

feat: add openweather service when occured error open data

---

.github/workflows/build.yml
src/controllers/connector/github/GithubController.ts
src/providers/connector/open_data/OpenDataProvider.ts

chore: analyze 기능 주석 처리

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/notion/test_api_connector_delete_block_and_page.ts
test/features/api/connector/notion/test_api_connector_notion_get_page_contents.ts

notion page 조회 및 block 삭제 로직

---

src/providers/connector/google_scholar/GoogleScholarProvider.ts

fix: total undefined

---

packages/api/tsconfig.json

fix: source-map set to be false

---

src/providers/connector/google_scholar/GoogleScholarProvider.ts
src/providers/connector/google_search/GoogleSearchProvider.ts

fix: organic_result is empty

---

nestia.config.ts

feat: nestia config 수정

---

src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/google_calendar/GoogleCalendarProvider.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

슬랙 유저 프로필 상세 조회 기능 추가

---

package-lock.json
package.json
src/api/structures/connector/google_drive/IGoogleDrive.ts
src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/google_drive/GoogleDriveController.ts
src/providers/connector/google_drive/GoogleDriveProvider.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/google_drive/test_api_connector_google_drive.ts
test/features/api/connector/marp/test_api_connector_marp.ts

슬랙 Prerequisite 정보 수정

---

src/api/structures/connector/google_calendar/IGoogleCalendar.ts

fix: google calendar description

---

.github/workflows/build.yml
.github/workflows/version.yml
src/api/structures/connector/google_drive/IGoogleDrive.ts
src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts

fix slack replace function and some properties

---

src/controllers/connector/airport_information/AirportInformationModule.ts
src/providers/connector/airport_information/AirportInformationProvider.ts

refactor: aws module use

---

src/api/structures/connector/github/IGithub.ts
src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

get files connector in slack

---

src/api/structures/connector/google_calendar/IGoogleCalendar.ts
src/providers/connector/google_calendar/GoogleCalendarProvider.ts

fix: calendar timezone

---

src/providers/connector/slack/SlackProvider.ts

refactor: slack message source

---

src/providers/connector/slack/SlackProvider.ts

refactor: slack message preconfigured

---

.github/pull_request_template.md
package-lock.json
package.json
src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts
src/providers/connector/slack/SlackTemplateProvider.ts
test/features/api/connector/slack/test_api_connector_slack_vote.ts

voting feature in slack

---

src/providers/connector/slack/SlackProvider.ts

fix: fix token

---

src/providers/connector/stable_diffusion_beta/StableDiffusionBetaProvider.ts

fix: sdxl-beta deprecated spec

---

src/controllers/connector/slack/SlackController.ts

fix: fix interactivity body decorator again

---

src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts

fix: fix interactivity body decorator finally

---

src/api/structures/connector/jira/IJira.ts
test/features/api/connector/jira/test_api_connector_jira_get_issues.ts

fix: fix jira type more detail

---

src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts

슬랙 대댓글에 대한 프롬프트 수정 및 프로퍼티 추가

---

src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts

feat: add members to replies

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/crunchbase/CrunchbaseController.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/crunchbase/CrunchbaseExample.ts
src/providers/connector/crunchbase/CrunchbaseProvider.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/crunchbase/test_api_connector_crunchbase.ts
test/features/api/connector/github/test_api_connector_github_read_pull_request_diff.ts
test/features/api/connector/notion/test_api_connector_append_blocks_by_markdown.ts

크런치베이스 및 노션 일부 로직 수정

---

src/api/structures/connector/crunchbase/ICrunchbase.ts
src/controllers/connector/crunchbase/CrunchbaseController.ts

fix: crunchbase 조회를 10번까지 재시도하게 수정

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts

feat: add notion page link

---

src/controllers/connector/crunchbase/CrunchbaseController.ts

fix: fix timelimit value

---

src/controllers/connector/x/XController.ts

fix: function description change

---

src/api/structures/connector/x/IX.ts

refactor: description for summay tweet input

---

src/providers/connector/x/XProvider.ts

feat: add logger for x provider

---

.github/workflows/build.yml
src/api/structures/connector/x/IX.ts
src/controllers/connector/x/XController.ts
src/providers/connector/x/XProvider.ts
test/features/api/connector/x/test_api_connector_x_prepare_summarize.ts
test/features/api/connector/x/test_api_connector_x_summarize.ts

feat: seperate logic for rag

---

src/api/structures/connector/x/IX.ts
src/controllers/connector/x/XController.ts
src/providers/connector/x/XProvider.ts

feat: add logging

---

src/controllers/connector/x/XController.ts

fix: description for summary

---

src/api/structures/connector/x/IX.ts

fix: description for x interface

---

src/controllers/connector/x/XController.ts

fix: aavoid multiple request

---

package.json
packages/api/.gitignore
src/executable/indexing_swagger_files.ts
website/.gitignore

feat: add index of swagger files

---

src/controllers/connector/x/XController.ts

feat: enhance prompt

---

tsconfig.json

fix: fix exclude statement in tsconfig.json

---

src/controllers/connector/x/XController.ts

fix: prompt

---

src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack_get_user_groups.ts

usergroup에 대한 정규식 추가 및 Promise.all로 속도 향상

---

src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts

feat: add speaker property for channel histories

---

src/controllers/connector/x/XController.ts
src/providers/connector/x/XProvider.ts

fix: tweet undefined and chunk document unnecessary filed exclude

---

src/providers/connector/slack/SlackProvider.ts

fix: 유저 목록이 조회되게 수정

---

src/providers/connector/x/XProvider.ts

fix: get document bug

---

src/controllers/connector/x/XController.ts

fix: prompt for prepare summary

---

src/controllers/connector/github/GithubController.ts

feat: 파일 생성 및 수정시 base64가 안오도록 주석 추가

---

README.md

fix: remove description of SelectorParam

---

.github/workflows/version.yml
CONTRIBUTING.md
package.json
src/api/structures/connector/google_drive/IGoogleDrive.ts
src/executable/swagger-to-google-sheets.ts
src/providers/connector/google_sheet/GoogleSheetProvider.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
src/providers/connector/korea_eximbank/KoreaEximbankProvider.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/google_slides/test_api_connector_google_slides.ts
test/features/api/connector/google_slides/test_api_connector_google_slides_export_presentation.ts
website/package.json

스웨거 배포 자동화

---

README.md

Translate readme file

---

src/api/structures/connector/jira/IJira.ts
src/controllers/connector/jira/JiraController.ts
src/providers/connector/jira/JiraProvider.ts
test/features/api/connector/jira/test_api_connector_jira_create_issue_by_markdown.ts

지라 익명 타입 제거

---

src/api/structures/connector/jira/IJira.ts
src/controllers/connector/jira/JiraController.ts
src/providers/connector/jira/JiraProvider.ts
test/features/api/connector/jira/test_api_connector_jira_create_issue_by_markdown.ts

Revert "Revert "지라 익명 타입 제거""

---

src/api/structures/connector/jira/IJira.ts
src/providers/connector/jira/JiraProvider.ts
test/features/api/connector/jira/test_api_connector_jira_update_issue.ts

feat: add markdown format updating jira issue connector

---

src/controllers/connector/calendly/CalendlyController.ts

add icon of calendly

---

src/api/structures/connector/gmail/IGmail.ts
src/controllers/connector/gmail/GmailController.ts
src/providers/connector/gmail/GmailProvider.ts
test/features/api/connector/gmail/test_api_connector_gmail.ts
test/features/api/connector/gmail/test_api_connector_gmail_send_email_with_file.ts

fix gmail test

---

src/executable/swagger-to-google-sheets.ts

feat: 0번째 인덱스를 추가하고 이미지를 추가

---

src/executable/swagger-to-google-sheets.ts

fix: 폴더 아이디 수정

---

src/api/structures/connector/crunchbase/ICrunchbase.ts

fix: crunchbase 타입 수정

---

src/api/structures/connector/crunchbase/ICrunchbase.ts

fix: add nullable

---

src/executable/swagger-to-google-sheets.ts

구글 시트의 색상 지정, 필터 추가, 빈칸 체크 기능 추가

---

src/executable/swagger-to-google-sheets.ts

feat: add sale info to google sheets

---

src/api/structures/connector/google_calendar/IGoogleCalendar.ts
src/providers/connector/google_calendar/GoogleCalendarProvider.ts
test/features/api/connector/google_calendar/test_api_connector_google_calendar.ts

refactor: change type for date-time

---

src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

update slack message

---

nestia.config.ts
src/controllers/connector/calendly/CalendlyController.ts
src/controllers/connector/chatbot/ChatbotController.ts
src/controllers/connector/github/GithubController.ts
src/controllers/connector/notion/NotionController.ts
src/controllers/connector/slack/SlackController.ts

누락된 아이콘 및 설명 수정 및 Sale 등록 건

---

.github/workflows/build.yml

fix: exclude all x test code when build

---

src/api/structures/connector/open_data/IMOLIT.ts
src/providers/connector/arxiv_search/ArxivSearchProvider.ts
src/providers/connector/open_data/OpenDataProvider.ts
src/utils/convertAllPropertyToString.ts
src/utils/convertXmlToJson.ts
test/features/api/connector/open_data/test_api_connector_open_data.ts

[DRAFT] 공공데이터 업데이트에 따른 수정

---

src/providers/connector/slack/SlackProvider.ts

fix: 에러가 발생했을 때 최소한 어떤 스코프로 인한 것인지 추적이라도 되게 하기

---

src/api/structures/connector/google_docs/IGoogleDocs.ts
src/api/structures/connector/google_drive/IGoogleDrive.ts
src/api/structures/connector/google_sheet/IGoogleSheet.ts
src/api/structures/connector/google_slides/IGoogleSlides.ts

scope를 모두 Drive에서 Drive.file로 변경

---

.github/workflows/build.yml
test/features/api/connector/reddit/test_api_connector_reddit.ts

fix: reddit은 테스트 코드에서 제외

---

.github/workflows/build.yml
src/controllers/connector/ConnectorModule.ts
test/features/api/connector/reddit/test_api_connector_reddit.ts

reddit 커넥터 원복

---

src/api/structures/connector/youtube_search/IYoutubeSearch.ts
src/providers/connector/youtube_search/YoutubeSearchProvider.ts

fix: unsupported bug

---

src/api/structures/connector/innoforest/IInnoforest.ts
src/providers/connector/innoforest/InnoforestProvider.ts
test/features/api/connector/innoforest/test_api_connector_innoforest.ts

feat: 시스템 에러도 정상 응답으로 내보내기

---

src/controllers/connector/innoforest/InnoforestController.ts

fix: 주석만 수정하여 다시 한 번 배포 시도

---

src/api/structures/connector/youtube_search/IYoutubeSearch.ts
src/providers/connector/youtube_search/YoutubeSearchProvider.ts

fix: filter auto generated video

---

src/controllers/connector/youtube_search/YoutubeSearchController.ts

refactor: enhance prompt for get transcript connector

---

src/api/structures/connector/youtube_search/IYoutubeSearch.ts
src/providers/connector/youtube_search/YoutubeSearchProvider.ts

fix: delete description field for youtube search connector response

---

src/api/structures/connector/innoforest/IInnoforest.ts
src/controllers/connector/notion/NotionController.ts

fix: number 문제 해결을 위해 int64 제거

---

src/api/structures/connector/kakao_talk/IKakaoTalk.ts
src/providers/connector/kakao_talk/KakaoTalkProvider.ts
test/features/api/connector/kakao_talk/test_api_connector_kakao_talk_memo.ts

fix kakao refresh

---

src/api/structures/connector/prompt/IPrompt.ts
src/providers/connector/prompt/PromptProvider.ts
test/inhouse/api/connector/prompt/test_api_connector_prompt.ts

refactor: prompt node model change claude to openai

---

package-lock.json
package.json
src/ConnectorGlobal.ts
src/api/structures/connector/web_crawler/IWebCrawler.ts
src/controllers/connector/ConnectorModule.ts
src/controllers/connector/web_crawler/WebCrawlerController.ts
src/controllers/connector/web_crawler/WebCrawlerModule.ts
src/providers/connector/web_crawler/WebCrawlerProvider.ts
test/features/api/connector/web_crawler/test_api_connector_web_crawler_get_content.ts

web crawler connector

---

src/providers/connector/airport_information/AirportInformationProvider.ts

fix: get airport information bug

---

src/controllers/connector/youtube_search/YoutubeSearchController.ts

refactor: enhance prompt for youtube transcript

---

src/controllers/connector/youtube_search/YoutubeSearchController.ts

feat: add description for youtube search endpoint

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/notion/test_api_connector_notion_update_page_title.ts

update notion title

---

.env
.github/workflows/build.yml
src/ConnectorGlobal.ts
src/api/structures/connector/youtube_search/IYoutubeSearch.ts
src/controllers/connector/youtube_search/YoutubeSearchController.ts
src/providers/connector/youtube_search/YoutubeSearchProvider.ts
test/features/api/connector/youtube/test_api_connector_youtube_official.ts

feat: add youtube official api for search video

---

.github/workflows/build.yml
docker-compose-test.yml
init.sql
prisma/schema/schema-slack.prisma
src/api/structures/connector/jira/IJira.ts
src/api/structures/connector/reddit/IReddit.ts
src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/jira/test_api_connector_jira_create_issue_by_markdown.ts
test/features/api/connector/jira/test_api_connector_jira_get_issues.ts
test/features/api/connector/slack/test_api_connector_slack.ts

slack user DB

---

src/providers/connector/slack/SlackProvider.ts

에러 로그가 쌓이지 않게 serialize 다시 하기

---

src/api/structures/connector/x/IX.ts
src/controllers/connector/x/XController.ts
src/providers/connector/x/XProvider.ts
test/features/api/connector/x/test_api_connector_x_general_search.ts

fix: request interface and response interface for general tweet search

---

src/api/structures/connector/x/IX.ts
src/providers/connector/x/XProvider.ts
test/features/api/connector/x/test_api_connector_x_general_search.ts

fix: delete secret and add thumbnail field

---

src/providers/connector/x/XProvider.ts

fix: add defensive code for empty data for general search

---

.github/workflows/build.yml
src/providers/connector/slack/SlackProvider.ts

fix: 첫 조회 시 프로필 이미지 누락되는 이슈 수정

---

package-lock.json
package.json
src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/notion/test_api_connector_delete_block_and_page.ts
test/features/api/connector/notion/test_api_connector_notion.ts
test/features/api/connector/notion/test_api_connector_notion_get_page_contents.ts

feat: get page content for markdown format

---

src/controllers/connector/articles/ArticlesController.ts

add prompt for blog scenario

---

src/api/structures/connector/articles/IArticle.ts
src/controllers/connector/articles/ArticlesController.ts

add prerequisite decorator and prompt to article controller

---

src/api/structures/connector/articles/IArticle.ts
src/controllers/connector/articles/ArticlesController.ts

feat: Add a description to distinguish between detailed and list queries

---

src/providers/connector/prompt/PromptProvider.ts

fix: add logging for empty response for llm

---

src/providers/connector/kakao_talk/KakaoTalkProvider.ts
src/providers/connector/slack/SlackProvider.ts

unuse databases of slack

---

src/api/structures/connector/github/IGithub.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/github/GithubProvider.ts

GitHub diff return error object if file change is more than 300

---

docs/ERD.md
prisma/schema/schema-article.prisma
prisma/schema/schema-provider.prisma
src/api/structures/connector/articles/IArticle.ts
src/providers/connector/article/BbsArticleExportProvider.ts
src/providers/connector/article/DocumentProvider.ts
src/providers/connector/kakao_talk/KakaoTalkProvider.ts
src/providers/connector/notion/NotionProvider.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/articles/test_api_connector_article.ts

add provider table for exports

---

src/api/structures/connector/articles/IArticle.ts
src/providers/connector/article/BbsArticleSnapshotProvider.ts

filter deleted exports

---

src/providers/connector/article/DocumentProvider.ts

fix: fix provider logic by removing id props

---

test/features/api/connector/articles/test_api_connector_article.ts

fix: fix test code

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/notion/test_api_connector_notion_create_gallery_database.ts
test/features/api/connector/notion/test_api_connector_notion_create_gallery_item.ts

create Notion gallary view database items

---

src/controllers/connector/notion/NotionController.ts

fix: notion prompt

---

src/api/structures/connector/articles/IArticle.ts
src/api/structures/connector/articles/IArticleExport.ts
src/api/structures/connector/google_docs/IGoogleDocs.ts
src/controllers/connector/articles/ArticlesController.ts
src/controllers/connector/google-docs/GoogleDocsController.ts
src/providers/connector/article/BbsArticleExportProvider.ts
src/providers/connector/article/DocumentProvider.ts
src/providers/connector/google_docs/GoogleDocsProvider.ts
src/providers/connector/google_drive/GoogleDriveProvider.ts
test/features/api/connector/articles/test_api_connector_article.ts
test/features/api/connector/google_docs/test_api_connector_google_docs.ts

update sync logic and `exports to google docs` connector

---

src/providers/connector/notion/NotionProvider.ts

fix: notion gallery image markdown parsing bug

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/notion/test_api_connector_notion_create_gallery_item.ts

fix: notion gallery database create item logic change

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/notion/test_api_connector_notion_create_gallery_item.ts

fix: notion gallery database create item request interface

---

src/api/structures/connector/notion/INotion.ts
src/controllers/connector/notion/NotionController.ts

fix: notion gallery database create item request prompt

---

src/api/structures/connector/google_docs/IGoogleDocs.ts
src/controllers/connector/articles/ArticlesController.ts
src/controllers/connector/google-docs/GoogleDocsController.ts
src/providers/connector/article/DocumentProvider.ts
src/providers/connector/google_docs/GoogleDocsProvider.ts
test/features/api/connector/articles/test_api_connector_article.ts
test/features/api/connector/google_docs/test_api_connector_google_docs.ts

sync google docs

---

src/controllers/connector/articles/ArticlesController.ts

feat: add some prompt for connector

---

src/api/structures/connector/articles/IArticle.ts
src/api/structures/connector/articles/IArticleExport.ts
src/api/structures/connector/jira/IJira.ts
src/controllers/connector/jira/JiraController.ts
src/providers/connector/article/DocumentProvider.ts

add detailed comments for jira issue

---

src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

test: add test code and if ts value is undefined, it throw error

---

src/api/structures/connector/google_image/IGoogleImage.ts
src/controllers/connector/ConnectorModule.ts
src/controllers/connector/google_image/GoogleImageController.ts
src/controllers/connector/google_image/GoogleImageModule.ts
src/providers/google_image/GoogleImageProvider.ts
test/features/api/connector/google_image/test_api_connector_google_image.ts

feat: add google image search connector

---

src/api/structures/connector/jira/IJira.ts
src/api/structures/connector/slack/ISlack.ts
src/providers/connector/jira/JiraProvider.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

update slack message and jira issue type

---

src/ConnectorGlobal.ts
src/api/structures/connector/articles/IArticle.ts
src/api/structures/connector/articles/IArticleExport.ts
src/api/structures/connector/dev.to/IDevTo.ts
src/controllers/connector/articles/ArticlesController.ts
src/providers/connector/article/BbsArticleExportProvider.ts
src/providers/connector/article/DocumentProvider.ts
src/providers/connector/dev.to/DevToProvider.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/articles/test_api_connector_article.ts
test/features/api/connector/sweet_tracker/test_api_connector_sweet_tracker.ts

article channels

---

src/providers/connector/x/XProvider.ts

feat: x issue

---

src/api/structures/connector/jira/IJira.ts

add comments for issue link

---

src/api/structures/connector/articles/IArticle.ts
src/api/structures/connector/dev.to/IDevTo.ts

change dev_to secretKey name

---

src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

feat: add `user_profile` prop to message inferface in slack

---

src/api/structures/connector/kakao_map/IKakaoMap.ts
src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

add comments for kakao map query

---

src/api/structures/connector/articles/IArticle.ts

feat: set optional fields to snapshot format and title in article DB

---

src/api/structures/connector/articles/IArticle.ts
src/providers/connector/dev.to/DevToProvider.ts

getting dev to key from sandbox id

---

src/api/structures/connector/airport_information/IAirportInformation.ts
src/controllers/connector/airport_information/AirportInformationController.ts

fix: prompt for airport information

---

src/providers/connector/dev.to/DevToProvider.ts

fix key object in dev.to

---

src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

get slack im channel when get users

---

test/features/api/connector/articles/test_api_connector_article.ts

test of searching by title in article connector

---

src/api/structures/connector/reddit/IReddit.ts
src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts

add comments for slack user pagination

---

src/api/structures/connector/google_hotel/IGoogleHotel.ts
src/api/structures/connector/google_shopping/IGoogleShopping.ts
src/controllers/connector/google_hotel/GoolgeHotelController.ts
src/controllers/connector/google_shopping/google_shopping_aladine/GoogleShoppingAladinController.ts
src/controllers/connector/google_shopping/google_shopping_aliexpress/GoogleShoppingAliexpressController.ts
src/controllers/connector/google_shopping/google_shopping_coupang/GoogleShoppingCoupangController.ts
src/controllers/connector/google_shopping/google_shopping_eql/GoogleShoppingEqlController.ts
src/controllers/connector/google_shopping/google_shopping_iherb/GoogleShoppingIherbController.ts
src/controllers/connector/google_shopping/google_shopping_market_kurly/GoogleShoppingMarketKurlyController.ts
src/controllers/connector/google_shopping/google_shopping_musinsa/GoogleShoppingMusinsaController.ts
src/controllers/connector/google_shopping/google_shopping_oco/GoogleShoppingOcoController.ts
src/controllers/connector/google_shopping/google_shopping_olive_young/GoogleShoppingOliveYoungController.ts
src/controllers/connector/google_shopping/google_shopping_twenty_nine_cenetimeter/GoogleShoppingTwentyNineCentimeterController.ts
src/controllers/connector/google_shopping/google_shopping_uniqlo/GoogleShoppingUniqloController.ts
src/controllers/connector/google_shopping/google_shopping_yes_twenty_four/GoogleShoppingYesTwentyFourController.ts

fix: prompt for must only contain one keyword

---

src/controllers/connector/youtube_search/YoutubeSearchController.ts

fix: prompt for call youtube official api

---

src/api/structures/connector/airport_information/IAirportInformation.ts
src/api/structures/connector/google_hotel/IGoogleHotel.ts
src/api/structures/connector/google_shopping/IGoogleShopping.ts
src/controllers/connector/airport_information/AirportInformationController.ts
src/controllers/connector/google_hotel/GoolgeHotelController.ts
src/controllers/connector/google_shopping/google_shopping_aladine/GoogleShoppingAladinController.ts
src/controllers/connector/google_shopping/google_shopping_aliexpress/GoogleShoppingAliexpressController.ts
src/controllers/connector/google_shopping/google_shopping_coupang/GoogleShoppingCoupangController.ts
src/controllers/connector/google_shopping/google_shopping_eql/GoogleShoppingEqlController.ts
src/controllers/connector/google_shopping/google_shopping_iherb/GoogleShoppingIherbController.ts
src/controllers/connector/google_shopping/google_shopping_market_kurly/GoogleShoppingMarketKurlyController.ts
src/controllers/connector/google_shopping/google_shopping_musinsa/GoogleShoppingMusinsaController.ts
src/controllers/connector/google_shopping/google_shopping_oco/GoogleShoppingOcoController.ts
src/controllers/connector/google_shopping/google_shopping_olive_young/GoogleShoppingOliveYoungController.ts
src/controllers/connector/google_shopping/google_shopping_twenty_nine_cenetimeter/GoogleShoppingTwentyNineCentimeterController.ts
src/controllers/connector/google_shopping/google_shopping_uniqlo/GoogleShoppingUniqloController.ts
src/controllers/connector/google_shopping/google_shopping_yes_twenty_four/GoogleShoppingYesTwentyFourController.ts

fix: prompt for keyword

---

src/api/structures/connector/google_docs/IGoogleDocs.ts
src/controllers/connector/google-docs/GoogleDocsController.ts
src/providers/connector/google_docs/GoogleDocsProvider.ts

add comments for creation of empty google docs file

---

src/api/structures/connector/slack/ISlack.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

add slack im channel id to get DM functions

---

src/ConnectorGlobal.ts
src/controllers/connector/airport_information/AirportInformationModule.ts
src/controllers/connector/aws/AwsController.ts
src/controllers/connector/aws/AwsModule.ts
src/controllers/connector/rag/RagModule.ts
src/controllers/connector/x/XModule.ts
src/providers/connector/airport_information/AirportInformationProvider.ts
src/providers/connector/aws/AwsProvider.ts
src/providers/connector/csv/CsvProvider.ts
src/providers/connector/dall_e_3/DallE3Provider.ts
src/providers/connector/excel/ExcelProvider.ts
src/providers/connector/github/GithubProvider.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
src/providers/connector/hancell/HancellProvider.ts
src/providers/connector/marketing/MarketingCopyGeneratorProvider.ts
src/providers/connector/marp/MarpProvider.ts
src/providers/connector/rag/RagProvider.ts
src/providers/connector/stable_diffusion_beta/StableDiffusionBetaProvider.ts
src/providers/connector/x/XProvider.ts
test/features/api/connector/github/test_api_connector_github_analyze.ts
test/features/api/connector/google_slides/test_api_connector_google_slides_by_types.ts

using aws namespace

---

src/providers/connector/gmail/GmailProvider.ts

fix send gmail for file sending

---

src/providers/connector/csv/CsvProvider.ts

fix: csv write error

---

src/api/structures/connector/jira/IJira.ts
src/controllers/connector/github/GithubController.ts
src/controllers/connector/google-docs/GoogleDocsController.ts
test/features/api/connector/jira/test_api_connector_jira_comments.ts

remove jira properties and google docs create empty file and update connectors

---

src/controllers/connector/gmail/GmailController.ts
src/controllers/connector/gmail/GmailModule.ts
src/controllers/connector/google-docs/GoogleDocsController.ts
src/controllers/connector/google-docs/GoogleDocsModule.ts
src/controllers/connector/google-sheet/GoogleSheetController.ts
src/controllers/connector/google-sheet/GoogleSheetModule.ts
src/controllers/connector/google_ads/GoogleAdsController.ts
src/controllers/connector/google_ads/GoogleAdsModule.ts
src/controllers/connector/google_calendar/GoogleCalendarController.ts
src/controllers/connector/google_calendar/GoogleCalendarModule.ts
src/controllers/connector/google_drive/GoogleDriveController.ts
src/controllers/connector/google_drive/GoogleDriveModule.ts
src/controllers/connector/google_slides/GoogleSlidesController.ts
src/controllers/connector/google_slides/GoogleSlidesModule.ts
src/controllers/connector/internal/google/GoogleController.ts
src/controllers/connector/internal/google/GoogleModule.ts
src/providers/connector/article/DocumentProvider.ts
src/providers/connector/gmail/GmailProvider.ts
src/providers/connector/google_ads/GoogleAdsProvider.ts
src/providers/connector/google_calendar/GoogleCalendarProvider.ts
src/providers/connector/google_docs/GoogleDocsProvider.ts
src/providers/connector/google_drive/GoogleDriveProvider.ts
src/providers/connector/google_sheet/GoogleSheetProvider.ts
src/providers/connector/google_slides/GoogleSlidesProvider.ts
src/providers/internal/google/GoogleProvider.ts
test/features/api/connector/google_slides/test_api_connector_google_slides_by_types.ts

google namespace

---

src/controllers/connector/notion/NotionController.ts
src/providers/connector/notion/NotionProvider.ts
test/features/api/connector/notion/test_api_connector_notion.ts
test/features/api/connector/notion/test_api_connector_notion_update_page_title.ts

fix: remove create page function not markdown format

---

src/api/structures/connector/slack/ISlack.ts

fix: add im history scope to slack secret

---

src/api/structures/connector/google_sheet/IGoogleSheet.ts
src/controllers/connector/google-sheet/GoogleSheetController.ts
src/providers/connector/google_sheet/GoogleSheetProvider.ts
test/features/api/connector/google_sheet/test_api_connector_append_google_sheet.ts

fix: fix google sheet range

---

nestia.config.ts

fix: remove zoom swaager

---

src/api/structures/connector/slack/ISlack.ts
src/controllers/connector/slack/SlackController.ts
src/providers/connector/slack/SlackProvider.ts
test/features/api/connector/slack/test_api_connector_slack.ts

add function to delete slack message

---

src/controllers/connector/arxiv_search/ArxivSearchController.ts
src/controllers/connector/aws/AwsController.ts
src/controllers/connector/calendly/CalendlyController.ts
src/controllers/connector/crunchbase/CrunchbaseController.ts
src/controllers/connector/dall_e_3/DallE3Controller.ts
src/controllers/connector/daum/DaumController.ts
src/controllers/connector/discord/DiscordController.ts
src/controllers/connector/excel/ExcelController.ts
src/controllers/connector/github/GithubController.ts
src/controllers/connector/gmail/GmailController.ts
src/controllers/connector/google_ads/GoogleAdsController.ts
src/controllers/connector/google_calendar/GoogleCalendarController.ts
src/controllers/connector/google_flight/GoogleFlightController.ts
src/controllers/connector/google_map/GoogleMapController.ts
src/controllers/connector/google_scholar/GoogleScholarController.ts
src/controllers/connector/google_search_career/GoogleSearchCareerController.ts
src/controllers/connector/google_shopping/google_shopping_aladine/GoogleShoppingAladinController.ts
src/controllers/connector/google_shopping/google_shopping_yes_twenty_four/GoogleShoppingYesTwentyFourController.ts
src/controllers/connector/innoforest/InnoforestController.ts
src/controllers/connector/swal/article/ArticleController.ts

feat: remove some of select benchmark decorators #823

---

src/controllers/connector/ai_search/AISearchController.ts
src/controllers/connector/aws/AwsController.ts
src/controllers/connector/calendly/CalendlyController.ts
src/controllers/connector/chatbot/ChatbotController.ts
src/controllers/connector/crunchbase/CrunchbaseController.ts
src/controllers/connector/discord/DiscordController.ts
src/controllers/connector/extract/KeywordExtractController.ts
src/controllers/connector/figma/FigmaController.ts
src/controllers/connector/google_ads/GoogleAdsController.ts
src/controllers/connector/google_slides/GoogleSlidesController.ts
src/controllers/connector/google_trend/GoogleTrendController.ts
src/controllers/connector/imweb/ImwebController.ts
src/controllers/connector/innoforest/InnoforestController.ts
src/controllers/connector/kakao_navi/KakaoNaviController.ts
src/controllers/connector/kakao_talk/KakaoTalkController.ts
src/controllers/connector/korea_eximbank/KoreaEximbankController.ts
src/controllers/connector/llm/LlmController.ts
src/controllers/connector/open_data/OpenDataController.ts
src/controllers/connector/prompts/PromptController.ts
src/controllers/connector/short_link/ShortLinkController.ts
src/controllers/connector/similarweb/SimilarwebController.ts
src/controllers/connector/sort/RankController.ts
src/controllers/connector/stable_diffustion_beta/StableDiffusionBetaController.ts
src/controllers/connector/story_generator/StoryGeneratorController.ts
src/controllers/connector/story_image_generator/StoryImageGeneratorController.ts
src/controllers/connector/student_report_generator/StudentReportGeneratorController.ts
src/controllers/connector/sweet_tracker/SweetTrackerController.ts
src/controllers/connector/tool/ToolController.ts
src/controllers/connector/typeform/TypeformController.ts
src/controllers/connector/zoom/ZoomController.ts

Releated Issue: https://github.com/wrtnio/connectors/issues/821

fix: filtering unnecessary connector list

---

src/controllers/connector/youtube_search/YoutubeSearchController.ts

fix: serp api youtube search revival

---

test/features/api/connector/youtube/test_api_connector_youtube_official.ts
test/features/api/connector/youtube/test_api_connector_youtube_search.ts
test/features/api/connector/youtube/test_api_connector_youtube_transcript.ts

fix: build error

---

src/providers/connector/google_shopping/GoogleShoppingProvider.ts
test/benchmark/call/scenarios/asher/scenario_minecraft_hosting_aws_to_email_or_slack.ts
test/benchmark/call/scenarios/owen/scenario_ginseng_youtube_to_excel.ts

fix: delete console log

---

src/controllers/connector/excel/ExcelController.ts
src/controllers/connector/github/GithubController.ts
src/controllers/connector/jira/JiraController.ts
src/controllers/connector/slack/SlackController.ts
src/controllers/connector/swal/article/ArticleController.ts
src/controllers/connector/youtube_search/YoutubeSearchController.ts

fix: connector function description length

---

src/providers/connector/slack/SlackProvider.ts

fix: slack get im channel next cursor bug

---

nestia.config.ts

fix: nestia config ts

---

nestia.config.ts
src/controllers/connector/ConnectorModule.ts
src/controllers/connector/google_shopping/google_shopping_amazon/GoogleShoppingAmazonController.ts
src/controllers/connector/google_shopping/google_shopping_amazon/GoogleShoppingAmazonModule.ts
src/controllers/connector/google_shopping/google_shopping_ebay/GoogleShoppingEbayController.ts
src/controllers/connector/google_shopping/google_shopping_ebay/GoogleShoppingEbayModule.ts
src/controllers/connector/google_shopping/google_shopping_walmart/GoogleShoppingWalmartController.ts
src/controllers/connector/google_shopping/google_shopping_walmart/GoogleShoppingWalmartModule.ts
src/providers/connector/google_shopping/GoogleShoppingProvider.ts
test/features/api/connector/google_shopping/test_api_connector_google_shopping.ts

fix: shopping restore

---

src/controllers/connector/github/GithubController.ts

fix: get issue prompt for get owner name

---

src/api/structures/connector/github/IGithub.ts
src/api/structures/connector/notion/INotion.ts
src/controllers/connector/github/GithubController.ts
src/providers/connector/github/GithubProvider.ts
src/providers/connector/notion/NotionProvider.ts
src/providers/connector/swal/article/DocumentProvider.ts
test/features/api/connector/github/test_api_connector_github_issues_get_comments.ts
test/features/api/connector/github/test_api_connector_github_repository_get_issue_detail.ts
test/features/api/connector/github/test_api_connector_github_repository_get_issues.ts
test/features/api/connector/notion/test_api_connector_delete_block_and_page.ts
test/features/api/connector/notion/test_api_connector_notion.ts
test/features/api/connector/notion/test_api_connector_notion_update_page_title.ts
test/features/api/connector/swal/article/test_api_connector_article.ts

Return a message if user do not find a repository or parent page in GitHub and Notion

---

test/inhouse/api/connector/dall_e_3/test_api_connector_dall_e_3.ts

fix:build error

---

src/api/structures/connector/github/IGithub.ts

add scope for writing comments to PR

---

src/api/structures/connector/github/IGithub.ts
src/providers/connector/github/GithubProvider.ts

feat: set scope more bigger

---

.github/workflows/build.yml
src/api/structures/connector/github/IGithub.ts
src/providers/connector/github/GithubProvider.ts

feat: fix github review comment types

---

src/utils/retry.ts

fix: retry function name

---

src/api/structures/connector/github/IGithub.ts

feat: add comments more

---

src/api/structures/connector/github/IGithub.ts
src/providers/connector/github/GithubProvider.ts

feat: change string to object github diff connector

---

src/controllers/connector/github/GithubController.ts

fix: description length

---

package-lock.json
package.json

fix: upgrade dd-trace version

---

package-lock.json
package.json

dd trace version up

---

.github/workflows/release.yml

- fix release.yml
- NPM_PUBLISH to NPM_TOKEN

chore: fix NPM_PUBLISH to NPM_TOKEN

---

packages/daum_blog/package.json

chore: fix daum blog package name

---

packages/slack/src/slack/SlackService.ts

- Request by @kakasoo 
- remove `slice(1)` in getReplies function.

fix: getReplies in SlackService

---

.github/workflows/build.yml
connectors-list.json
deploy/list-connectors.mjs
package.json
pnpm-lock.yaml

Add script to automatically generate a JSON list of connector packages
with their names and versions. This script runs in the prepare step
to ensure the list stays updated.# Test before submitting
We need this for agentica cli list up connectors feature

feat: add list-connectors script

---

.github/workflows/spell-check.yml
typos.toml

added spell checker like Agentica does

feat(ci): add spellcheck ci

---

packages/youtube_official_search/README.md
packages/youtube_search/README.md
packages/youtube_transcript/README.md

This is a minor README update related to issue #977

README updates for YouTube Connector packages

---

packages/github/src/github/GithubService.ts
packages/github/src/structures/IGithubService.ts
packages/github/test/TestGlobal.ts
packages/github/test/features/test_github_get_commit.ts
packages/github/test/features/test_github_get_follow.ts
packages/github/test/features/test_github_get_users.ts
packages/github/test/features/test_github_review.ts

- change Refresh token to Access token in GithubService

fix: change Refresh token to Access token in GithubService

---

connectors-list.json
pnpm-lock.yaml

- update connector list version.
- update pnpm-lock

chore: update lock and connector list

---

.github/workflows/build.yml
connectors-list.json
packages/google_flight/package.json
packages/google_flight/src/google_flight/GoogleFlightService.ts
packages/google_flight/src/structures/IGoogleFlightService.ts
packages/google_flight/test/TestGlobal.ts
packages/google_flight/test/features/test_google_flight_with_short_io.ts
packages/google_trend/src/google_trend/GoogleTrendService.ts
packages/google_trend/src/structures/IGoogleTrendService.ts
packages/google_trend/test/features/test_google_trend.ts
packages/short_io/src/short_io/ShortIoService.ts
packages/short_io/src/structures/IShortIoService.ts
packages/short_io/test/features/test_short_io.ts
pnpm-lock.yaml

- Add `domain` property to the constructor of `ShortIoService`.
- Adopt the `LinkShortener` to `GoogleFlightService`.
- Fix the Response type of `GoogleFlightService`.

fix: adopt shortener to google flight
